name: Deploy to AWS Lambda and S3

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET_NAME: r2d2-frontend
  LAMBDA_FUNCTION_NAME: r2d2_prototype

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Verify AWS CLI
        run: aws --version
      
      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt

      - name: Build and package backend code
        run: |
          cd backend
          zip -r backend.zip .
      
      - name: Build React application
        run: |
          cd stream-app
          npm install
          npm run build
      
      - name: Deploy to AWS Lambda
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --zip-file fileb://backend/backend.zip
          
      - name: Deploy frontend to S3
        run: |
          aws s3 sync stream-app/build/ s3://${{ env.S3_BUCKET_NAME }} --delete